# rime明月拼音简化字方案特化配置
# path: ~/.config/ibus/rime/luna_pinyin_simp.custom.yaml (linux-ibus)
# path: ~/Library/Rime/luna_pinyin_simp.custom.yaml (mac)
# emoji支持需要https://github.com/rime/rime-emoji

patch:
  switches:
    - name: ascii_mode
      reset: 1                        # 默认英文
      states: ["中", "英"]
    - name: full_shape
      reset: 0                        # 默认半角
      states: ["半角", "全角"]
    - name: zh_simp
      reset: 1                        # 默认简体
      states: ["漢字", "汉字"]

  recognizer/patterns/punct: "^i([A-Za-z]+)$"
  punctuator:
      import_preset: default
      symbols:
        "imail": "guoqiang.mail@qq.com"
        "itel": "18091411674"
      half_shape:                     # 半角模式使用部分全角字符
        "\\" : "、"
        "/"  : "/"
        "!"  : "!"
        "?"  : "?"
        "%"  : "%"
        "*"  : "*"
        "<"  : "《"
        ">"  : "》"

  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: none                        # 取消表情包注释
